var str = "Javascript is easy";
console.log(str.indexOf("a"));
console.log(str.lastIndexOf("a"));
console.log(str.indexOf("k"));
console.log(str.charAt(3));
console.log(str.substring(5, 8));
console.log(str.substr(5, 3));
console.log(str.split("a"));
console.log(str.split("a", 2));
console.log(str.length);